name: Deploy Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v2
    - name: Deploy Pages
      run: |
        git config --local user.email "strategy.unit@nhs.net"
        git config --local user.name "Strategy Unit (GitHub Actions)"

        git checkout -b gh-pages
        git rm workshop.Rmd
        git rm README.md
        git rm -r .github
        mv workshop.html index.html
        git add .
        git commit -m "redeploy pages"
        git push --force origin gh-pages
